/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


/**
 * AssessmentReport
 */

public class AssessmentReport {
  @SerializedName("ShortName")
  private String shortName = null;

  @SerializedName("ReportLink")
  private String reportLink = null;

  public AssessmentReport shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
 
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public AssessmentReport reportLink(String reportLink) {
    this.reportLink = reportLink;
    return this;
  }

   /**
   * Get reportLink
   * @return reportLink
  **/
 
  public String getReportLink() {
    return reportLink;
  }

  public void setReportLink(String reportLink) {
    this.reportLink = reportLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssessmentReport assessmentReport = (AssessmentReport) o;
    return Objects.equals(this.shortName, assessmentReport.shortName) &&
        Objects.equals(this.reportLink, assessmentReport.reportLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shortName, reportLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssessmentReport {\n");
    
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    reportLink: ").append(toIndentedString(reportLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

