/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.joda.time.DateTime;
import org.my.dayforce.model.AssessmentScore;

/**
 * CandidateAssessmentScores
 */

public class CandidateAssessmentScores {
  @SerializedName("CreationDateTime")
  private DateTime creationDateTime = null;

  @SerializedName("CandidateAssessmentGuid")
  private UUID candidateAssessmentGuid = null;

  @SerializedName("OverallScore")
  private AssessmentScore overallScore = null;

  @SerializedName("IsRecommended")
  private Boolean isRecommended = null;

  @SerializedName("DetailedScores")
  private List<AssessmentScore> detailedScores = new ArrayList<AssessmentScore>();

  public CandidateAssessmentScores creationDateTime(DateTime creationDateTime) {
    this.creationDateTime = creationDateTime;
    return this;
  }

   /**
   * Get creationDateTime
   * @return creationDateTime
  **/
 
  public DateTime getCreationDateTime() {
    return creationDateTime;
  }

  public void setCreationDateTime(DateTime creationDateTime) {
    this.creationDateTime = creationDateTime;
  }

  public CandidateAssessmentScores candidateAssessmentGuid(UUID candidateAssessmentGuid) {
    this.candidateAssessmentGuid = candidateAssessmentGuid;
    return this;
  }

   /**
   * Get candidateAssessmentGuid
   * @return candidateAssessmentGuid
  **/
 
  public UUID getCandidateAssessmentGuid() {
    return candidateAssessmentGuid;
  }

  public void setCandidateAssessmentGuid(UUID candidateAssessmentGuid) {
    this.candidateAssessmentGuid = candidateAssessmentGuid;
  }

  public CandidateAssessmentScores overallScore(AssessmentScore overallScore) {
    this.overallScore = overallScore;
    return this;
  }

   /**
   * Get overallScore
   * @return overallScore
  **/
 
  public AssessmentScore getOverallScore() {
    return overallScore;
  }

  public void setOverallScore(AssessmentScore overallScore) {
    this.overallScore = overallScore;
  }

  public CandidateAssessmentScores isRecommended(Boolean isRecommended) {
    this.isRecommended = isRecommended;
    return this;
  }

   /**
   * Get isRecommended
   * @return isRecommended
  **/
 
  public Boolean getIsRecommended() {
    return isRecommended;
  }

  public void setIsRecommended(Boolean isRecommended) {
    this.isRecommended = isRecommended;
  }

  public CandidateAssessmentScores detailedScores(List<AssessmentScore> detailedScores) {
    this.detailedScores = detailedScores;
    return this;
  }

  public CandidateAssessmentScores addDetailedScoresItem(AssessmentScore detailedScoresItem) {
    this.detailedScores.add(detailedScoresItem);
    return this;
  }

   /**
   * Get detailedScores
   * @return detailedScores
  **/
 
  public List<AssessmentScore> getDetailedScores() {
    return detailedScores;
  }

  public void setDetailedScores(List<AssessmentScore> detailedScores) {
    this.detailedScores = detailedScores;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CandidateAssessmentScores candidateAssessmentScores = (CandidateAssessmentScores) o;
    return Objects.equals(this.creationDateTime, candidateAssessmentScores.creationDateTime) &&
        Objects.equals(this.candidateAssessmentGuid, candidateAssessmentScores.candidateAssessmentGuid) &&
        Objects.equals(this.overallScore, candidateAssessmentScores.overallScore) &&
        Objects.equals(this.isRecommended, candidateAssessmentScores.isRecommended) &&
        Objects.equals(this.detailedScores, candidateAssessmentScores.detailedScores);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDateTime, candidateAssessmentGuid, overallScore, isRecommended, detailedScores);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CandidateAssessmentScores {\n");
    
    sb.append("    creationDateTime: ").append(toIndentedString(creationDateTime)).append("\n");
    sb.append("    candidateAssessmentGuid: ").append(toIndentedString(candidateAssessmentGuid)).append("\n");
    sb.append("    overallScore: ").append(toIndentedString(overallScore)).append("\n");
    sb.append("    isRecommended: ").append(toIndentedString(isRecommended)).append("\n");
    sb.append("    detailedScores: ").append(toIndentedString(detailedScores)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

