/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.joda.time.DateTime;
import org.my.dayforce.model.AssessmentReport;

/**
 * CandidateAssessmentReports
 */

public class CandidateAssessmentReports {
  @SerializedName("CreationDateTime")
  private DateTime creationDateTime = null;

  @SerializedName("CandidateAssessmentGuid")
  private UUID candidateAssessmentGuid = null;

  @SerializedName("Reports")
  private List<AssessmentReport> reports = new ArrayList<AssessmentReport>();

  public CandidateAssessmentReports creationDateTime(DateTime creationDateTime) {
    this.creationDateTime = creationDateTime;
    return this;
  }

   /**
   * Get creationDateTime
   * @return creationDateTime
  **/
 
  public DateTime getCreationDateTime() {
    return creationDateTime;
  }

  public void setCreationDateTime(DateTime creationDateTime) {
    this.creationDateTime = creationDateTime;
  }

  public CandidateAssessmentReports candidateAssessmentGuid(UUID candidateAssessmentGuid) {
    this.candidateAssessmentGuid = candidateAssessmentGuid;
    return this;
  }

   /**
   * Get candidateAssessmentGuid
   * @return candidateAssessmentGuid
  **/
 
  public UUID getCandidateAssessmentGuid() {
    return candidateAssessmentGuid;
  }

  public void setCandidateAssessmentGuid(UUID candidateAssessmentGuid) {
    this.candidateAssessmentGuid = candidateAssessmentGuid;
  }

  public CandidateAssessmentReports reports(List<AssessmentReport> reports) {
    this.reports = reports;
    return this;
  }

  public CandidateAssessmentReports addReportsItem(AssessmentReport reportsItem) {
    this.reports.add(reportsItem);
    return this;
  }

   /**
   * Get reports
   * @return reports
  **/
 
  public List<AssessmentReport> getReports() {
    return reports;
  }

  public void setReports(List<AssessmentReport> reports) {
    this.reports = reports;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CandidateAssessmentReports candidateAssessmentReports = (CandidateAssessmentReports) o;
    return Objects.equals(this.creationDateTime, candidateAssessmentReports.creationDateTime) &&
        Objects.equals(this.candidateAssessmentGuid, candidateAssessmentReports.candidateAssessmentGuid) &&
        Objects.equals(this.reports, candidateAssessmentReports.reports);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDateTime, candidateAssessmentGuid, reports);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CandidateAssessmentReports {\n");
    
    sb.append("    creationDateTime: ").append(toIndentedString(creationDateTime)).append("\n");
    sb.append("    candidateAssessmentGuid: ").append(toIndentedString(candidateAssessmentGuid)).append("\n");
    sb.append("    reports: ").append(toIndentedString(reports)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

