/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import java.util.UUID;
import org.joda.time.DateTime;
import org.my.dayforce.model.DocumentType;
import org.my.dayforce.model.UploadedBy;

/**
 * Document
 */

public class Document {
  @SerializedName("DocumentGUID")
  private UUID documentGUID = null;

  @SerializedName("DocumentName")
  private String documentName = null;

  @SerializedName("DocumentType")
  private DocumentType documentType = null;

  @SerializedName("FileName")
  private String fileName = null;

  @SerializedName("UploadedDate")
  private DateTime uploadedDate = null;

  @SerializedName("UploadedBy")
  private UploadedBy uploadedBy = null;

  public Document documentGUID(UUID documentGUID) {
    this.documentGUID = documentGUID;
    return this;
  }

   /**
   * Get documentGUID
   * @return documentGUID
  **/
 
  public UUID getDocumentGUID() {
    return documentGUID;
  }

  public void setDocumentGUID(UUID documentGUID) {
    this.documentGUID = documentGUID;
  }

  public Document documentName(String documentName) {
    this.documentName = documentName;
    return this;
  }

   /**
   * Get documentName
   * @return documentName
  **/
 
  public String getDocumentName() {
    return documentName;
  }

  public void setDocumentName(String documentName) {
    this.documentName = documentName;
  }

  public Document documentType(DocumentType documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
 
  public DocumentType getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentType documentType) {
    this.documentType = documentType;
  }

  public Document fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
 
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public Document uploadedDate(DateTime uploadedDate) {
    this.uploadedDate = uploadedDate;
    return this;
  }

   /**
   * Get uploadedDate
   * @return uploadedDate
  **/
 
  public DateTime getUploadedDate() {
    return uploadedDate;
  }

  public void setUploadedDate(DateTime uploadedDate) {
    this.uploadedDate = uploadedDate;
  }

  public Document uploadedBy(UploadedBy uploadedBy) {
    this.uploadedBy = uploadedBy;
    return this;
  }

   /**
   * Get uploadedBy
   * @return uploadedBy
  **/
 
  public UploadedBy getUploadedBy() {
    return uploadedBy;
  }

  public void setUploadedBy(UploadedBy uploadedBy) {
    this.uploadedBy = uploadedBy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Document document = (Document) o;
    return Objects.equals(this.documentGUID, document.documentGUID) &&
        Objects.equals(this.documentName, document.documentName) &&
        Objects.equals(this.documentType, document.documentType) &&
        Objects.equals(this.fileName, document.fileName) &&
        Objects.equals(this.uploadedDate, document.uploadedDate) &&
        Objects.equals(this.uploadedBy, document.uploadedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentGUID, documentName, documentType, fileName, uploadedDate, uploadedBy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Document {\n");
    
    sb.append("    documentGUID: ").append(toIndentedString(documentGUID)).append("\n");
    sb.append("    documentName: ").append(toIndentedString(documentName)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    uploadedDate: ").append(toIndentedString(uploadedDate)).append("\n");
    sb.append("    uploadedBy: ").append(toIndentedString(uploadedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

