/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;

/**
 * EarningType
 */

public class EarningType {
  @SerializedName("CodeName")
  private String codeName = null;

  @SerializedName("IsGLAllocatedDebit")
  private Boolean isGLAllocatedDebit = null;

  @SerializedName("IsGLAllocatedCredit")
  private Boolean isGLAllocatedCredit = null;

  @SerializedName("XRefCode")
  private String xrefCode = null;

  @SerializedName("ShortName")
  private String shortName = null;

  @SerializedName("LongName")
  private String longName = null;

  @SerializedName("LastModifiedTimestamp")
  private DateTime lastModifiedTimestamp = null;

  public EarningType codeName(String codeName) {
    this.codeName = codeName;
    return this;
  }

   /**
   * Get codeName
   * @return codeName
  **/
 
  public String getCodeName() {
    return codeName;
  }

  public void setCodeName(String codeName) {
    this.codeName = codeName;
  }

  public EarningType isGLAllocatedDebit(Boolean isGLAllocatedDebit) {
    this.isGLAllocatedDebit = isGLAllocatedDebit;
    return this;
  }

   /**
   * Get isGLAllocatedDebit
   * @return isGLAllocatedDebit
  **/
 
  public Boolean getIsGLAllocatedDebit() {
    return isGLAllocatedDebit;
  }

  public void setIsGLAllocatedDebit(Boolean isGLAllocatedDebit) {
    this.isGLAllocatedDebit = isGLAllocatedDebit;
  }

  public EarningType isGLAllocatedCredit(Boolean isGLAllocatedCredit) {
    this.isGLAllocatedCredit = isGLAllocatedCredit;
    return this;
  }

   /**
   * Get isGLAllocatedCredit
   * @return isGLAllocatedCredit
  **/
 
  public Boolean getIsGLAllocatedCredit() {
    return isGLAllocatedCredit;
  }

  public void setIsGLAllocatedCredit(Boolean isGLAllocatedCredit) {
    this.isGLAllocatedCredit = isGLAllocatedCredit;
  }

  public EarningType xrefCode(String xrefCode) {
    this.xrefCode = xrefCode;
    return this;
  }

   /**
   * Get xrefCode
   * @return xrefCode
  **/
 
  public String getXrefCode() {
    return xrefCode;
  }

  public void setXrefCode(String xrefCode) {
    this.xrefCode = xrefCode;
  }

  public EarningType shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
 
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public EarningType longName(String longName) {
    this.longName = longName;
    return this;
  }

   /**
   * Get longName
   * @return longName
  **/
 
  public String getLongName() {
    return longName;
  }

  public void setLongName(String longName) {
    this.longName = longName;
  }

  public EarningType lastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Get lastModifiedTimestamp
   * @return lastModifiedTimestamp
  **/
 
  public DateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EarningType earningType = (EarningType) o;
    return Objects.equals(this.codeName, earningType.codeName) &&
        Objects.equals(this.isGLAllocatedDebit, earningType.isGLAllocatedDebit) &&
        Objects.equals(this.isGLAllocatedCredit, earningType.isGLAllocatedCredit) &&
        Objects.equals(this.xrefCode, earningType.xrefCode) &&
        Objects.equals(this.shortName, earningType.shortName) &&
        Objects.equals(this.longName, earningType.longName) &&
        Objects.equals(this.lastModifiedTimestamp, earningType.lastModifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codeName, isGLAllocatedDebit, isGLAllocatedCredit, xrefCode, shortName, longName, lastModifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EarningType {\n");
    
    sb.append("    codeName: ").append(toIndentedString(codeName)).append("\n");
    sb.append("    isGLAllocatedDebit: ").append(toIndentedString(isGLAllocatedDebit)).append("\n");
    sb.append("    isGLAllocatedCredit: ").append(toIndentedString(isGLAllocatedCredit)).append("\n");
    sb.append("    xrefCode: ").append(toIndentedString(xrefCode)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    longName: ").append(toIndentedString(longName)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

