/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;
import org.my.dayforce.model.DFEthnicity;

/**
 * EmployeeEthnicity
 */

public class EmployeeEthnicity {
  @SerializedName("EffectiveStart")
  private DateTime effectiveStart = null;

  @SerializedName("EffectiveEnd")
  private DateTime effectiveEnd = null;

  @SerializedName("Ethnicity")
  private DFEthnicity ethnicity = null;

  @SerializedName("ManagerEthnicity")
  private DFEthnicity managerEthnicity = null;

  @SerializedName("LastModifiedTimestamp")
  private DateTime lastModifiedTimestamp = null;

  public EmployeeEthnicity effectiveStart(DateTime effectiveStart) {
    this.effectiveStart = effectiveStart;
    return this;
  }

   /**
   * Get effectiveStart
   * @return effectiveStart
  **/
 
  public DateTime getEffectiveStart() {
    return effectiveStart;
  }

  public void setEffectiveStart(DateTime effectiveStart) {
    this.effectiveStart = effectiveStart;
  }

  public EmployeeEthnicity effectiveEnd(DateTime effectiveEnd) {
    this.effectiveEnd = effectiveEnd;
    return this;
  }

   /**
   * Get effectiveEnd
   * @return effectiveEnd
  **/
 
  public DateTime getEffectiveEnd() {
    return effectiveEnd;
  }

  public void setEffectiveEnd(DateTime effectiveEnd) {
    this.effectiveEnd = effectiveEnd;
  }

  public EmployeeEthnicity ethnicity(DFEthnicity ethnicity) {
    this.ethnicity = ethnicity;
    return this;
  }

   /**
   * Get ethnicity
   * @return ethnicity
  **/
 
  public DFEthnicity getEthnicity() {
    return ethnicity;
  }

  public void setEthnicity(DFEthnicity ethnicity) {
    this.ethnicity = ethnicity;
  }

  public EmployeeEthnicity managerEthnicity(DFEthnicity managerEthnicity) {
    this.managerEthnicity = managerEthnicity;
    return this;
  }

   /**
   * Get managerEthnicity
   * @return managerEthnicity
  **/
 
  public DFEthnicity getManagerEthnicity() {
    return managerEthnicity;
  }

  public void setManagerEthnicity(DFEthnicity managerEthnicity) {
    this.managerEthnicity = managerEthnicity;
  }

  public EmployeeEthnicity lastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Get lastModifiedTimestamp
   * @return lastModifiedTimestamp
  **/
 
  public DateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeEthnicity employeeEthnicity = (EmployeeEthnicity) o;
    return Objects.equals(this.effectiveStart, employeeEthnicity.effectiveStart) &&
        Objects.equals(this.effectiveEnd, employeeEthnicity.effectiveEnd) &&
        Objects.equals(this.ethnicity, employeeEthnicity.ethnicity) &&
        Objects.equals(this.managerEthnicity, employeeEthnicity.managerEthnicity) &&
        Objects.equals(this.lastModifiedTimestamp, employeeEthnicity.lastModifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(effectiveStart, effectiveEnd, ethnicity, managerEthnicity, lastModifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeEthnicity {\n");
    
    sb.append("    effectiveStart: ").append(toIndentedString(effectiveStart)).append("\n");
    sb.append("    effectiveEnd: ").append(toIndentedString(effectiveEnd)).append("\n");
    sb.append("    ethnicity: ").append(toIndentedString(ethnicity)).append("\n");
    sb.append("    managerEthnicity: ").append(toIndentedString(managerEthnicity)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

