/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;
import org.my.dayforce.model.Course;
import org.my.dayforce.model.EmployeeTrainingProgram;

/**
 * EmployeeCourse
 */

public class EmployeeCourse {
  @SerializedName("StartDate")
  private DateTime startDate = null;

  @SerializedName("CompletionDate")
  private DateTime completionDate = null;

  @SerializedName("CertificationExpiryDate")
  private DateTime certificationExpiryDate = null;

  @SerializedName("Course")
  private Course course = null;

  @SerializedName("EmployeeTrainingProgram")
  private EmployeeTrainingProgram employeeTrainingProgram = null;

  @SerializedName("CertificationNumber")
  private String certificationNumber = null;

  @SerializedName("Comment")
  private String comment = null;

  @SerializedName("Score")
  private String score = null;

  @SerializedName("PassFail")
  private String passFail = null;

  @SerializedName("LastModifiedTimestamp")
  private DateTime lastModifiedTimestamp = null;

  public EmployeeCourse startDate(DateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
 
  public DateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(DateTime startDate) {
    this.startDate = startDate;
  }

  public EmployeeCourse completionDate(DateTime completionDate) {
    this.completionDate = completionDate;
    return this;
  }

   /**
   * Get completionDate
   * @return completionDate
  **/
 
  public DateTime getCompletionDate() {
    return completionDate;
  }

  public void setCompletionDate(DateTime completionDate) {
    this.completionDate = completionDate;
  }

  public EmployeeCourse certificationExpiryDate(DateTime certificationExpiryDate) {
    this.certificationExpiryDate = certificationExpiryDate;
    return this;
  }

   /**
   * Get certificationExpiryDate
   * @return certificationExpiryDate
  **/
 
  public DateTime getCertificationExpiryDate() {
    return certificationExpiryDate;
  }

  public void setCertificationExpiryDate(DateTime certificationExpiryDate) {
    this.certificationExpiryDate = certificationExpiryDate;
  }

  public EmployeeCourse course(Course course) {
    this.course = course;
    return this;
  }

   /**
   * Get course
   * @return course
  **/
 
  public Course getCourse() {
    return course;
  }

  public void setCourse(Course course) {
    this.course = course;
  }

  public EmployeeCourse employeeTrainingProgram(EmployeeTrainingProgram employeeTrainingProgram) {
    this.employeeTrainingProgram = employeeTrainingProgram;
    return this;
  }

   /**
   * Get employeeTrainingProgram
   * @return employeeTrainingProgram
  **/
 
  public EmployeeTrainingProgram getEmployeeTrainingProgram() {
    return employeeTrainingProgram;
  }

  public void setEmployeeTrainingProgram(EmployeeTrainingProgram employeeTrainingProgram) {
    this.employeeTrainingProgram = employeeTrainingProgram;
  }

  public EmployeeCourse certificationNumber(String certificationNumber) {
    this.certificationNumber = certificationNumber;
    return this;
  }

   /**
   * Get certificationNumber
   * @return certificationNumber
  **/
 
  public String getCertificationNumber() {
    return certificationNumber;
  }

  public void setCertificationNumber(String certificationNumber) {
    this.certificationNumber = certificationNumber;
  }

  public EmployeeCourse comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
 
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public EmployeeCourse score(String score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
 
  public String getScore() {
    return score;
  }

  public void setScore(String score) {
    this.score = score;
  }

  public EmployeeCourse passFail(String passFail) {
    this.passFail = passFail;
    return this;
  }

   /**
   * Get passFail
   * @return passFail
  **/
 
  public String getPassFail() {
    return passFail;
  }

  public void setPassFail(String passFail) {
    this.passFail = passFail;
  }

  public EmployeeCourse lastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Get lastModifiedTimestamp
   * @return lastModifiedTimestamp
  **/
 
  public DateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeCourse employeeCourse = (EmployeeCourse) o;
    return Objects.equals(this.startDate, employeeCourse.startDate) &&
        Objects.equals(this.completionDate, employeeCourse.completionDate) &&
        Objects.equals(this.certificationExpiryDate, employeeCourse.certificationExpiryDate) &&
        Objects.equals(this.course, employeeCourse.course) &&
        Objects.equals(this.employeeTrainingProgram, employeeCourse.employeeTrainingProgram) &&
        Objects.equals(this.certificationNumber, employeeCourse.certificationNumber) &&
        Objects.equals(this.comment, employeeCourse.comment) &&
        Objects.equals(this.score, employeeCourse.score) &&
        Objects.equals(this.passFail, employeeCourse.passFail) &&
        Objects.equals(this.lastModifiedTimestamp, employeeCourse.lastModifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDate, completionDate, certificationExpiryDate, course, employeeTrainingProgram, certificationNumber, comment, score, passFail, lastModifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeCourse {\n");
    
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    completionDate: ").append(toIndentedString(completionDate)).append("\n");
    sb.append("    certificationExpiryDate: ").append(toIndentedString(certificationExpiryDate)).append("\n");
    sb.append("    course: ").append(toIndentedString(course)).append("\n");
    sb.append("    employeeTrainingProgram: ").append(toIndentedString(employeeTrainingProgram)).append("\n");
    sb.append("    certificationNumber: ").append(toIndentedString(certificationNumber)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    passFail: ").append(toIndentedString(passFail)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

