/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;

/**
 * EmployeeCANFederalTax
 */

public class EmployeeCANFederalTax {
  @SerializedName("EffectiveStart")
  private DateTime effectiveStart = null;

  @SerializedName("EffectiveEnd")
  private DateTime effectiveEnd = null;

  @SerializedName("TotalClaimAmount")
  private Double totalClaimAmount = null;

  @SerializedName("IsNonResident")
  private Boolean isNonResident = null;

  @SerializedName("MultipleEmployer")
  private Boolean multipleEmployer = null;

  @SerializedName("IncomeLessThanClaim")
  private Boolean incomeLessThanClaim = null;

  @SerializedName("DistrictTaxDeduction")
  private Double districtTaxDeduction = null;

  @SerializedName("AuthorizedTaxCredits")
  private Double authorizedTaxCredits = null;

  @SerializedName("EstimatedExpense")
  private Double estimatedExpense = null;

  @SerializedName("EstimatedRemuneration")
  private Double estimatedRemuneration = null;

  @SerializedName("AdditionalAmount")
  private Double additionalAmount = null;

  @SerializedName("PrescribedAreaDeduction")
  private Double prescribedAreaDeduction = null;

  @SerializedName("LastModifiedTimestamp")
  private DateTime lastModifiedTimestamp = null;

  public EmployeeCANFederalTax effectiveStart(DateTime effectiveStart) {
    this.effectiveStart = effectiveStart;
    return this;
  }

   /**
   * Get effectiveStart
   * @return effectiveStart
  **/
 
  public DateTime getEffectiveStart() {
    return effectiveStart;
  }

  public void setEffectiveStart(DateTime effectiveStart) {
    this.effectiveStart = effectiveStart;
  }

  public EmployeeCANFederalTax effectiveEnd(DateTime effectiveEnd) {
    this.effectiveEnd = effectiveEnd;
    return this;
  }

   /**
   * Get effectiveEnd
   * @return effectiveEnd
  **/
 
  public DateTime getEffectiveEnd() {
    return effectiveEnd;
  }

  public void setEffectiveEnd(DateTime effectiveEnd) {
    this.effectiveEnd = effectiveEnd;
  }

  public EmployeeCANFederalTax totalClaimAmount(Double totalClaimAmount) {
    this.totalClaimAmount = totalClaimAmount;
    return this;
  }

   /**
   * Get totalClaimAmount
   * @return totalClaimAmount
  **/
 
  public Double getTotalClaimAmount() {
    return totalClaimAmount;
  }

  public void setTotalClaimAmount(Double totalClaimAmount) {
    this.totalClaimAmount = totalClaimAmount;
  }

  public EmployeeCANFederalTax isNonResident(Boolean isNonResident) {
    this.isNonResident = isNonResident;
    return this;
  }

   /**
   * Get isNonResident
   * @return isNonResident
  **/
 
  public Boolean getIsNonResident() {
    return isNonResident;
  }

  public void setIsNonResident(Boolean isNonResident) {
    this.isNonResident = isNonResident;
  }

  public EmployeeCANFederalTax multipleEmployer(Boolean multipleEmployer) {
    this.multipleEmployer = multipleEmployer;
    return this;
  }

   /**
   * Get multipleEmployer
   * @return multipleEmployer
  **/
 
  public Boolean getMultipleEmployer() {
    return multipleEmployer;
  }

  public void setMultipleEmployer(Boolean multipleEmployer) {
    this.multipleEmployer = multipleEmployer;
  }

  public EmployeeCANFederalTax incomeLessThanClaim(Boolean incomeLessThanClaim) {
    this.incomeLessThanClaim = incomeLessThanClaim;
    return this;
  }

   /**
   * Get incomeLessThanClaim
   * @return incomeLessThanClaim
  **/
 
  public Boolean getIncomeLessThanClaim() {
    return incomeLessThanClaim;
  }

  public void setIncomeLessThanClaim(Boolean incomeLessThanClaim) {
    this.incomeLessThanClaim = incomeLessThanClaim;
  }

  public EmployeeCANFederalTax districtTaxDeduction(Double districtTaxDeduction) {
    this.districtTaxDeduction = districtTaxDeduction;
    return this;
  }

   /**
   * Get districtTaxDeduction
   * @return districtTaxDeduction
  **/
 
  public Double getDistrictTaxDeduction() {
    return districtTaxDeduction;
  }

  public void setDistrictTaxDeduction(Double districtTaxDeduction) {
    this.districtTaxDeduction = districtTaxDeduction;
  }

  public EmployeeCANFederalTax authorizedTaxCredits(Double authorizedTaxCredits) {
    this.authorizedTaxCredits = authorizedTaxCredits;
    return this;
  }

   /**
   * Get authorizedTaxCredits
   * @return authorizedTaxCredits
  **/
 
  public Double getAuthorizedTaxCredits() {
    return authorizedTaxCredits;
  }

  public void setAuthorizedTaxCredits(Double authorizedTaxCredits) {
    this.authorizedTaxCredits = authorizedTaxCredits;
  }

  public EmployeeCANFederalTax estimatedExpense(Double estimatedExpense) {
    this.estimatedExpense = estimatedExpense;
    return this;
  }

   /**
   * Get estimatedExpense
   * @return estimatedExpense
  **/
 
  public Double getEstimatedExpense() {
    return estimatedExpense;
  }

  public void setEstimatedExpense(Double estimatedExpense) {
    this.estimatedExpense = estimatedExpense;
  }

  public EmployeeCANFederalTax estimatedRemuneration(Double estimatedRemuneration) {
    this.estimatedRemuneration = estimatedRemuneration;
    return this;
  }

   /**
   * Get estimatedRemuneration
   * @return estimatedRemuneration
  **/
 
  public Double getEstimatedRemuneration() {
    return estimatedRemuneration;
  }

  public void setEstimatedRemuneration(Double estimatedRemuneration) {
    this.estimatedRemuneration = estimatedRemuneration;
  }

  public EmployeeCANFederalTax additionalAmount(Double additionalAmount) {
    this.additionalAmount = additionalAmount;
    return this;
  }

   /**
   * Get additionalAmount
   * @return additionalAmount
  **/
 
  public Double getAdditionalAmount() {
    return additionalAmount;
  }

  public void setAdditionalAmount(Double additionalAmount) {
    this.additionalAmount = additionalAmount;
  }

  public EmployeeCANFederalTax prescribedAreaDeduction(Double prescribedAreaDeduction) {
    this.prescribedAreaDeduction = prescribedAreaDeduction;
    return this;
  }

   /**
   * Get prescribedAreaDeduction
   * @return prescribedAreaDeduction
  **/
 
  public Double getPrescribedAreaDeduction() {
    return prescribedAreaDeduction;
  }

  public void setPrescribedAreaDeduction(Double prescribedAreaDeduction) {
    this.prescribedAreaDeduction = prescribedAreaDeduction;
  }

  public EmployeeCANFederalTax lastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Get lastModifiedTimestamp
   * @return lastModifiedTimestamp
  **/
 
  public DateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeCANFederalTax employeeCANFederalTax = (EmployeeCANFederalTax) o;
    return Objects.equals(this.effectiveStart, employeeCANFederalTax.effectiveStart) &&
        Objects.equals(this.effectiveEnd, employeeCANFederalTax.effectiveEnd) &&
        Objects.equals(this.totalClaimAmount, employeeCANFederalTax.totalClaimAmount) &&
        Objects.equals(this.isNonResident, employeeCANFederalTax.isNonResident) &&
        Objects.equals(this.multipleEmployer, employeeCANFederalTax.multipleEmployer) &&
        Objects.equals(this.incomeLessThanClaim, employeeCANFederalTax.incomeLessThanClaim) &&
        Objects.equals(this.districtTaxDeduction, employeeCANFederalTax.districtTaxDeduction) &&
        Objects.equals(this.authorizedTaxCredits, employeeCANFederalTax.authorizedTaxCredits) &&
        Objects.equals(this.estimatedExpense, employeeCANFederalTax.estimatedExpense) &&
        Objects.equals(this.estimatedRemuneration, employeeCANFederalTax.estimatedRemuneration) &&
        Objects.equals(this.additionalAmount, employeeCANFederalTax.additionalAmount) &&
        Objects.equals(this.prescribedAreaDeduction, employeeCANFederalTax.prescribedAreaDeduction) &&
        Objects.equals(this.lastModifiedTimestamp, employeeCANFederalTax.lastModifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(effectiveStart, effectiveEnd, totalClaimAmount, isNonResident, multipleEmployer, incomeLessThanClaim, districtTaxDeduction, authorizedTaxCredits, estimatedExpense, estimatedRemuneration, additionalAmount, prescribedAreaDeduction, lastModifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeCANFederalTax {\n");
    
    sb.append("    effectiveStart: ").append(toIndentedString(effectiveStart)).append("\n");
    sb.append("    effectiveEnd: ").append(toIndentedString(effectiveEnd)).append("\n");
    sb.append("    totalClaimAmount: ").append(toIndentedString(totalClaimAmount)).append("\n");
    sb.append("    isNonResident: ").append(toIndentedString(isNonResident)).append("\n");
    sb.append("    multipleEmployer: ").append(toIndentedString(multipleEmployer)).append("\n");
    sb.append("    incomeLessThanClaim: ").append(toIndentedString(incomeLessThanClaim)).append("\n");
    sb.append("    districtTaxDeduction: ").append(toIndentedString(districtTaxDeduction)).append("\n");
    sb.append("    authorizedTaxCredits: ").append(toIndentedString(authorizedTaxCredits)).append("\n");
    sb.append("    estimatedExpense: ").append(toIndentedString(estimatedExpense)).append("\n");
    sb.append("    estimatedRemuneration: ").append(toIndentedString(estimatedRemuneration)).append("\n");
    sb.append("    additionalAmount: ").append(toIndentedString(additionalAmount)).append("\n");
    sb.append("    prescribedAreaDeduction: ").append(toIndentedString(prescribedAreaDeduction)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

