/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;

/**
 * EmployeeHealthWellness
 */

public class EmployeeHealthWellness {
  @SerializedName("TobaccoUser")
  private String tobaccoUser = null;

  @SerializedName("DateLastSmoked")
  private DateTime dateLastSmoked = null;

  @SerializedName("EffectiveStart")
  private DateTime effectiveStart = null;

  @SerializedName("EffectiveEnd")
  private DateTime effectiveEnd = null;

  @SerializedName("LastModifiedTimestamp")
  private DateTime lastModifiedTimestamp = null;

  public EmployeeHealthWellness tobaccoUser(String tobaccoUser) {
    this.tobaccoUser = tobaccoUser;
    return this;
  }

   /**
   * Get tobaccoUser
   * @return tobaccoUser
  **/
 
  public String getTobaccoUser() {
    return tobaccoUser;
  }

  public void setTobaccoUser(String tobaccoUser) {
    this.tobaccoUser = tobaccoUser;
  }

  public EmployeeHealthWellness dateLastSmoked(DateTime dateLastSmoked) {
    this.dateLastSmoked = dateLastSmoked;
    return this;
  }

   /**
   * Get dateLastSmoked
   * @return dateLastSmoked
  **/
 
  public DateTime getDateLastSmoked() {
    return dateLastSmoked;
  }

  public void setDateLastSmoked(DateTime dateLastSmoked) {
    this.dateLastSmoked = dateLastSmoked;
  }

  public EmployeeHealthWellness effectiveStart(DateTime effectiveStart) {
    this.effectiveStart = effectiveStart;
    return this;
  }

   /**
   * Get effectiveStart
   * @return effectiveStart
  **/
 
  public DateTime getEffectiveStart() {
    return effectiveStart;
  }

  public void setEffectiveStart(DateTime effectiveStart) {
    this.effectiveStart = effectiveStart;
  }

  public EmployeeHealthWellness effectiveEnd(DateTime effectiveEnd) {
    this.effectiveEnd = effectiveEnd;
    return this;
  }

   /**
   * Get effectiveEnd
   * @return effectiveEnd
  **/
 
  public DateTime getEffectiveEnd() {
    return effectiveEnd;
  }

  public void setEffectiveEnd(DateTime effectiveEnd) {
    this.effectiveEnd = effectiveEnd;
  }

  public EmployeeHealthWellness lastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Get lastModifiedTimestamp
   * @return lastModifiedTimestamp
  **/
 
  public DateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeHealthWellness employeeHealthWellness = (EmployeeHealthWellness) o;
    return Objects.equals(this.tobaccoUser, employeeHealthWellness.tobaccoUser) &&
        Objects.equals(this.dateLastSmoked, employeeHealthWellness.dateLastSmoked) &&
        Objects.equals(this.effectiveStart, employeeHealthWellness.effectiveStart) &&
        Objects.equals(this.effectiveEnd, employeeHealthWellness.effectiveEnd) &&
        Objects.equals(this.lastModifiedTimestamp, employeeHealthWellness.lastModifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tobaccoUser, dateLastSmoked, effectiveStart, effectiveEnd, lastModifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeHealthWellness {\n");
    
    sb.append("    tobaccoUser: ").append(toIndentedString(tobaccoUser)).append("\n");
    sb.append("    dateLastSmoked: ").append(toIndentedString(dateLastSmoked)).append("\n");
    sb.append("    effectiveStart: ").append(toIndentedString(effectiveStart)).append("\n");
    sb.append("    effectiveEnd: ").append(toIndentedString(effectiveEnd)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

