/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;

/**
 * EmployeeAvailability
 */

public class EmployeeAvailability {
  @SerializedName("DateOfRequest")
  private DateTime dateOfRequest = null;

  @SerializedName("UnAvailable")
  private Boolean unAvailable = null;

  @SerializedName("IsDefault")
  private Boolean isDefault = null;

  @SerializedName("StartTime1")
  private String startTime1 = null;

  @SerializedName("EndTime1")
  private String endTime1 = null;

  @SerializedName("StartTime2")
  private String startTime2 = null;

  @SerializedName("EndTime2")
  private String endTime2 = null;

  public EmployeeAvailability dateOfRequest(DateTime dateOfRequest) {
    this.dateOfRequest = dateOfRequest;
    return this;
  }

   /**
   * Get dateOfRequest
   * @return dateOfRequest
  **/
 
  public DateTime getDateOfRequest() {
    return dateOfRequest;
  }

  public void setDateOfRequest(DateTime dateOfRequest) {
    this.dateOfRequest = dateOfRequest;
  }

  public EmployeeAvailability unAvailable(Boolean unAvailable) {
    this.unAvailable = unAvailable;
    return this;
  }

   /**
   * Get unAvailable
   * @return unAvailable
  **/
 
  public Boolean getUnAvailable() {
    return unAvailable;
  }

  public void setUnAvailable(Boolean unAvailable) {
    this.unAvailable = unAvailable;
  }

  public EmployeeAvailability isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Get isDefault
   * @return isDefault
  **/
 
  public Boolean getIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

  public EmployeeAvailability startTime1(String startTime1) {
    this.startTime1 = startTime1;
    return this;
  }

   /**
   * Get startTime1
   * @return startTime1
  **/
 
  public String getStartTime1() {
    return startTime1;
  }

  public void setStartTime1(String startTime1) {
    this.startTime1 = startTime1;
  }

  public EmployeeAvailability endTime1(String endTime1) {
    this.endTime1 = endTime1;
    return this;
  }

   /**
   * Get endTime1
   * @return endTime1
  **/
 
  public String getEndTime1() {
    return endTime1;
  }

  public void setEndTime1(String endTime1) {
    this.endTime1 = endTime1;
  }

  public EmployeeAvailability startTime2(String startTime2) {
    this.startTime2 = startTime2;
    return this;
  }

   /**
   * Get startTime2
   * @return startTime2
  **/
 
  public String getStartTime2() {
    return startTime2;
  }

  public void setStartTime2(String startTime2) {
    this.startTime2 = startTime2;
  }

  public EmployeeAvailability endTime2(String endTime2) {
    this.endTime2 = endTime2;
    return this;
  }

   /**
   * Get endTime2
   * @return endTime2
  **/
 
  public String getEndTime2() {
    return endTime2;
  }

  public void setEndTime2(String endTime2) {
    this.endTime2 = endTime2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeAvailability employeeAvailability = (EmployeeAvailability) o;
    return Objects.equals(this.dateOfRequest, employeeAvailability.dateOfRequest) &&
        Objects.equals(this.unAvailable, employeeAvailability.unAvailable) &&
        Objects.equals(this.isDefault, employeeAvailability.isDefault) &&
        Objects.equals(this.startTime1, employeeAvailability.startTime1) &&
        Objects.equals(this.endTime1, employeeAvailability.endTime1) &&
        Objects.equals(this.startTime2, employeeAvailability.startTime2) &&
        Objects.equals(this.endTime2, employeeAvailability.endTime2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateOfRequest, unAvailable, isDefault, startTime1, endTime1, startTime2, endTime2);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeAvailability {\n");
    
    sb.append("    dateOfRequest: ").append(toIndentedString(dateOfRequest)).append("\n");
    sb.append("    unAvailable: ").append(toIndentedString(unAvailable)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    startTime1: ").append(toIndentedString(startTime1)).append("\n");
    sb.append("    endTime1: ").append(toIndentedString(endTime1)).append("\n");
    sb.append("    startTime2: ").append(toIndentedString(startTime2)).append("\n");
    sb.append("    endTime2: ").append(toIndentedString(endTime2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

