/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;
import org.my.dayforce.model.TaxPropertyCollection;

/**
 * EmployeeCANTaxStatus
 */

public class EmployeeCANTaxStatus {
  @SerializedName("ProvinceCode")
  private String provinceCode = null;

  @SerializedName("EffectiveStart")
  private DateTime effectiveStart = null;

  @SerializedName("EffectiveEnd")
  private DateTime effectiveEnd = null;

  @SerializedName("TaxPropertyCollection")
  private TaxPropertyCollection taxPropertyCollection = null;

  @SerializedName("LastModifiedTimestamp")
  private DateTime lastModifiedTimestamp = null;

  public EmployeeCANTaxStatus provinceCode(String provinceCode) {
    this.provinceCode = provinceCode;
    return this;
  }

   /**
   * Get provinceCode
   * @return provinceCode
  **/
 
  public String getProvinceCode() {
    return provinceCode;
  }

  public void setProvinceCode(String provinceCode) {
    this.provinceCode = provinceCode;
  }

  public EmployeeCANTaxStatus effectiveStart(DateTime effectiveStart) {
    this.effectiveStart = effectiveStart;
    return this;
  }

   /**
   * Get effectiveStart
   * @return effectiveStart
  **/
 
  public DateTime getEffectiveStart() {
    return effectiveStart;
  }

  public void setEffectiveStart(DateTime effectiveStart) {
    this.effectiveStart = effectiveStart;
  }

  public EmployeeCANTaxStatus effectiveEnd(DateTime effectiveEnd) {
    this.effectiveEnd = effectiveEnd;
    return this;
  }

   /**
   * Get effectiveEnd
   * @return effectiveEnd
  **/
 
  public DateTime getEffectiveEnd() {
    return effectiveEnd;
  }

  public void setEffectiveEnd(DateTime effectiveEnd) {
    this.effectiveEnd = effectiveEnd;
  }

  public EmployeeCANTaxStatus taxPropertyCollection(TaxPropertyCollection taxPropertyCollection) {
    this.taxPropertyCollection = taxPropertyCollection;
    return this;
  }

   /**
   * Get taxPropertyCollection
   * @return taxPropertyCollection
  **/
 
  public TaxPropertyCollection getTaxPropertyCollection() {
    return taxPropertyCollection;
  }

  public void setTaxPropertyCollection(TaxPropertyCollection taxPropertyCollection) {
    this.taxPropertyCollection = taxPropertyCollection;
  }

  public EmployeeCANTaxStatus lastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Get lastModifiedTimestamp
   * @return lastModifiedTimestamp
  **/
 
  public DateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeCANTaxStatus employeeCANTaxStatus = (EmployeeCANTaxStatus) o;
    return Objects.equals(this.provinceCode, employeeCANTaxStatus.provinceCode) &&
        Objects.equals(this.effectiveStart, employeeCANTaxStatus.effectiveStart) &&
        Objects.equals(this.effectiveEnd, employeeCANTaxStatus.effectiveEnd) &&
        Objects.equals(this.taxPropertyCollection, employeeCANTaxStatus.taxPropertyCollection) &&
        Objects.equals(this.lastModifiedTimestamp, employeeCANTaxStatus.lastModifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provinceCode, effectiveStart, effectiveEnd, taxPropertyCollection, lastModifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeCANTaxStatus {\n");
    
    sb.append("    provinceCode: ").append(toIndentedString(provinceCode)).append("\n");
    sb.append("    effectiveStart: ").append(toIndentedString(effectiveStart)).append("\n");
    sb.append("    effectiveEnd: ").append(toIndentedString(effectiveEnd)).append("\n");
    sb.append("    taxPropertyCollection: ").append(toIndentedString(taxPropertyCollection)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

