/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;

/**
 * EmploymentStatusReason
 */

public class EmploymentStatusReason {
  @SerializedName("IsCompChangeReason")
  private Boolean isCompChangeReason = null;

  @SerializedName("IsLeaveReason")
  private Boolean isLeaveReason = null;

  @SerializedName("IsPositionChangeReason")
  private Boolean isPositionChangeReason = null;

  @SerializedName("IsTerminationReason")
  private Boolean isTerminationReason = null;

  @SerializedName("IsVoluntaryReason")
  private Boolean isVoluntaryReason = null;

  @SerializedName("XRefCode")
  private String xrefCode = null;

  @SerializedName("ShortName")
  private String shortName = null;

  @SerializedName("LongName")
  private String longName = null;

  @SerializedName("LastModifiedTimestamp")
  private DateTime lastModifiedTimestamp = null;

  public EmploymentStatusReason isCompChangeReason(Boolean isCompChangeReason) {
    this.isCompChangeReason = isCompChangeReason;
    return this;
  }

   /**
   * Get isCompChangeReason
   * @return isCompChangeReason
  **/
 
  public Boolean getIsCompChangeReason() {
    return isCompChangeReason;
  }

  public void setIsCompChangeReason(Boolean isCompChangeReason) {
    this.isCompChangeReason = isCompChangeReason;
  }

  public EmploymentStatusReason isLeaveReason(Boolean isLeaveReason) {
    this.isLeaveReason = isLeaveReason;
    return this;
  }

   /**
   * Get isLeaveReason
   * @return isLeaveReason
  **/
 
  public Boolean getIsLeaveReason() {
    return isLeaveReason;
  }

  public void setIsLeaveReason(Boolean isLeaveReason) {
    this.isLeaveReason = isLeaveReason;
  }

  public EmploymentStatusReason isPositionChangeReason(Boolean isPositionChangeReason) {
    this.isPositionChangeReason = isPositionChangeReason;
    return this;
  }

   /**
   * Get isPositionChangeReason
   * @return isPositionChangeReason
  **/
 
  public Boolean getIsPositionChangeReason() {
    return isPositionChangeReason;
  }

  public void setIsPositionChangeReason(Boolean isPositionChangeReason) {
    this.isPositionChangeReason = isPositionChangeReason;
  }

  public EmploymentStatusReason isTerminationReason(Boolean isTerminationReason) {
    this.isTerminationReason = isTerminationReason;
    return this;
  }

   /**
   * Get isTerminationReason
   * @return isTerminationReason
  **/
 
  public Boolean getIsTerminationReason() {
    return isTerminationReason;
  }

  public void setIsTerminationReason(Boolean isTerminationReason) {
    this.isTerminationReason = isTerminationReason;
  }

  public EmploymentStatusReason isVoluntaryReason(Boolean isVoluntaryReason) {
    this.isVoluntaryReason = isVoluntaryReason;
    return this;
  }

   /**
   * Get isVoluntaryReason
   * @return isVoluntaryReason
  **/
 
  public Boolean getIsVoluntaryReason() {
    return isVoluntaryReason;
  }

  public void setIsVoluntaryReason(Boolean isVoluntaryReason) {
    this.isVoluntaryReason = isVoluntaryReason;
  }

  public EmploymentStatusReason xrefCode(String xrefCode) {
    this.xrefCode = xrefCode;
    return this;
  }

   /**
   * Get xrefCode
   * @return xrefCode
  **/
 
  public String getXrefCode() {
    return xrefCode;
  }

  public void setXrefCode(String xrefCode) {
    this.xrefCode = xrefCode;
  }

  public EmploymentStatusReason shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
 
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public EmploymentStatusReason longName(String longName) {
    this.longName = longName;
    return this;
  }

   /**
   * Get longName
   * @return longName
  **/
 
  public String getLongName() {
    return longName;
  }

  public void setLongName(String longName) {
    this.longName = longName;
  }

  public EmploymentStatusReason lastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Get lastModifiedTimestamp
   * @return lastModifiedTimestamp
  **/
 
  public DateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmploymentStatusReason employmentStatusReason = (EmploymentStatusReason) o;
    return Objects.equals(this.isCompChangeReason, employmentStatusReason.isCompChangeReason) &&
        Objects.equals(this.isLeaveReason, employmentStatusReason.isLeaveReason) &&
        Objects.equals(this.isPositionChangeReason, employmentStatusReason.isPositionChangeReason) &&
        Objects.equals(this.isTerminationReason, employmentStatusReason.isTerminationReason) &&
        Objects.equals(this.isVoluntaryReason, employmentStatusReason.isVoluntaryReason) &&
        Objects.equals(this.xrefCode, employmentStatusReason.xrefCode) &&
        Objects.equals(this.shortName, employmentStatusReason.shortName) &&
        Objects.equals(this.longName, employmentStatusReason.longName) &&
        Objects.equals(this.lastModifiedTimestamp, employmentStatusReason.lastModifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isCompChangeReason, isLeaveReason, isPositionChangeReason, isTerminationReason, isVoluntaryReason, xrefCode, shortName, longName, lastModifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmploymentStatusReason {\n");
    
    sb.append("    isCompChangeReason: ").append(toIndentedString(isCompChangeReason)).append("\n");
    sb.append("    isLeaveReason: ").append(toIndentedString(isLeaveReason)).append("\n");
    sb.append("    isPositionChangeReason: ").append(toIndentedString(isPositionChangeReason)).append("\n");
    sb.append("    isTerminationReason: ").append(toIndentedString(isTerminationReason)).append("\n");
    sb.append("    isVoluntaryReason: ").append(toIndentedString(isVoluntaryReason)).append("\n");
    sb.append("    xrefCode: ").append(toIndentedString(xrefCode)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    longName: ").append(toIndentedString(longName)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

