/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;
import org.my.dayforce.model.EarningParameter;

/**
 * EmployeeEarningParameter
 */

public class EmployeeEarningParameter {
  @SerializedName("EarningParameter")
  private EarningParameter earningParameter = null;

  @SerializedName("Value")
  private Double value = null;

  @SerializedName("PayGroupValue")
  private Double payGroupValue = null;

  @SerializedName("LastModifiedTimestamp")
  private DateTime lastModifiedTimestamp = null;

  public EmployeeEarningParameter earningParameter(EarningParameter earningParameter) {
    this.earningParameter = earningParameter;
    return this;
  }

   /**
   * Get earningParameter
   * @return earningParameter
  **/
 
  public EarningParameter getEarningParameter() {
    return earningParameter;
  }

  public void setEarningParameter(EarningParameter earningParameter) {
    this.earningParameter = earningParameter;
  }

  public EmployeeEarningParameter value(Double value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
 
  public Double getValue() {
    return value;
  }

  public void setValue(Double value) {
    this.value = value;
  }

  public EmployeeEarningParameter payGroupValue(Double payGroupValue) {
    this.payGroupValue = payGroupValue;
    return this;
  }

   /**
   * Get payGroupValue
   * @return payGroupValue
  **/
 
  public Double getPayGroupValue() {
    return payGroupValue;
  }

  public void setPayGroupValue(Double payGroupValue) {
    this.payGroupValue = payGroupValue;
  }

  public EmployeeEarningParameter lastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Get lastModifiedTimestamp
   * @return lastModifiedTimestamp
  **/
 
  public DateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeEarningParameter employeeEarningParameter = (EmployeeEarningParameter) o;
    return Objects.equals(this.earningParameter, employeeEarningParameter.earningParameter) &&
        Objects.equals(this.value, employeeEarningParameter.value) &&
        Objects.equals(this.payGroupValue, employeeEarningParameter.payGroupValue) &&
        Objects.equals(this.lastModifiedTimestamp, employeeEarningParameter.lastModifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(earningParameter, value, payGroupValue, lastModifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeEarningParameter {\n");
    
    sb.append("    earningParameter: ").append(toIndentedString(earningParameter)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    payGroupValue: ").append(toIndentedString(payGroupValue)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

