/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;

/**
 * EmployeeProperty
 */

public class EmployeeProperty {
  @SerializedName("DataType")
  private Integer dataType = null;

  @SerializedName("EmployeeCardinality")
  private Integer employeeCardinality = null;

  @SerializedName("IsEditable")
  private Boolean isEditable = null;

  @SerializedName("DataTypeParam")
  private String dataTypeParam = null;

  @SerializedName("GenerateHREvent")
  private Boolean generateHREvent = null;

  @SerializedName("Sequence")
  private Integer sequence = null;

  @SerializedName("XRefCode")
  private String xrefCode = null;

  @SerializedName("ShortName")
  private String shortName = null;

  @SerializedName("LongName")
  private String longName = null;

  @SerializedName("LastModifiedTimestamp")
  private DateTime lastModifiedTimestamp = null;

  public EmployeeProperty dataType(Integer dataType) {
    this.dataType = dataType;
    return this;
  }

   /**
   * Get dataType
   * @return dataType
  **/
 
  public Integer getDataType() {
    return dataType;
  }

  public void setDataType(Integer dataType) {
    this.dataType = dataType;
  }

  public EmployeeProperty employeeCardinality(Integer employeeCardinality) {
    this.employeeCardinality = employeeCardinality;
    return this;
  }

   /**
   * Get employeeCardinality
   * @return employeeCardinality
  **/
 
  public Integer getEmployeeCardinality() {
    return employeeCardinality;
  }

  public void setEmployeeCardinality(Integer employeeCardinality) {
    this.employeeCardinality = employeeCardinality;
  }

  public EmployeeProperty isEditable(Boolean isEditable) {
    this.isEditable = isEditable;
    return this;
  }

   /**
   * Get isEditable
   * @return isEditable
  **/
 
  public Boolean getIsEditable() {
    return isEditable;
  }

  public void setIsEditable(Boolean isEditable) {
    this.isEditable = isEditable;
  }

  public EmployeeProperty dataTypeParam(String dataTypeParam) {
    this.dataTypeParam = dataTypeParam;
    return this;
  }

   /**
   * Get dataTypeParam
   * @return dataTypeParam
  **/
 
  public String getDataTypeParam() {
    return dataTypeParam;
  }

  public void setDataTypeParam(String dataTypeParam) {
    this.dataTypeParam = dataTypeParam;
  }

  public EmployeeProperty generateHREvent(Boolean generateHREvent) {
    this.generateHREvent = generateHREvent;
    return this;
  }

   /**
   * Get generateHREvent
   * @return generateHREvent
  **/
 
  public Boolean getGenerateHREvent() {
    return generateHREvent;
  }

  public void setGenerateHREvent(Boolean generateHREvent) {
    this.generateHREvent = generateHREvent;
  }

  public EmployeeProperty sequence(Integer sequence) {
    this.sequence = sequence;
    return this;
  }

   /**
   * Get sequence
   * @return sequence
  **/
 
  public Integer getSequence() {
    return sequence;
  }

  public void setSequence(Integer sequence) {
    this.sequence = sequence;
  }

  public EmployeeProperty xrefCode(String xrefCode) {
    this.xrefCode = xrefCode;
    return this;
  }

   /**
   * Get xrefCode
   * @return xrefCode
  **/
 
  public String getXrefCode() {
    return xrefCode;
  }

  public void setXrefCode(String xrefCode) {
    this.xrefCode = xrefCode;
  }

  public EmployeeProperty shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
 
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public EmployeeProperty longName(String longName) {
    this.longName = longName;
    return this;
  }

   /**
   * Get longName
   * @return longName
  **/
 
  public String getLongName() {
    return longName;
  }

  public void setLongName(String longName) {
    this.longName = longName;
  }

  public EmployeeProperty lastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Get lastModifiedTimestamp
   * @return lastModifiedTimestamp
  **/
 
  public DateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeProperty employeeProperty = (EmployeeProperty) o;
    return Objects.equals(this.dataType, employeeProperty.dataType) &&
        Objects.equals(this.employeeCardinality, employeeProperty.employeeCardinality) &&
        Objects.equals(this.isEditable, employeeProperty.isEditable) &&
        Objects.equals(this.dataTypeParam, employeeProperty.dataTypeParam) &&
        Objects.equals(this.generateHREvent, employeeProperty.generateHREvent) &&
        Objects.equals(this.sequence, employeeProperty.sequence) &&
        Objects.equals(this.xrefCode, employeeProperty.xrefCode) &&
        Objects.equals(this.shortName, employeeProperty.shortName) &&
        Objects.equals(this.longName, employeeProperty.longName) &&
        Objects.equals(this.lastModifiedTimestamp, employeeProperty.lastModifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataType, employeeCardinality, isEditable, dataTypeParam, generateHREvent, sequence, xrefCode, shortName, longName, lastModifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeProperty {\n");
    
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("    employeeCardinality: ").append(toIndentedString(employeeCardinality)).append("\n");
    sb.append("    isEditable: ").append(toIndentedString(isEditable)).append("\n");
    sb.append("    dataTypeParam: ").append(toIndentedString(dataTypeParam)).append("\n");
    sb.append("    generateHREvent: ").append(toIndentedString(generateHREvent)).append("\n");
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("    xrefCode: ").append(toIndentedString(xrefCode)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    longName: ").append(toIndentedString(longName)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

