/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;
import org.my.dayforce.model.EmploymentTypeConfig;

/**
 * EmployeeEmploymentType
 */

public class EmployeeEmploymentType {
  @SerializedName("EffectiveStart")
  private DateTime effectiveStart = null;

  @SerializedName("EffectiveEnd")
  private DateTime effectiveEnd = null;

  @SerializedName("EmploymentType")
  private EmploymentTypeConfig employmentType = null;

  @SerializedName("TaxPayerId")
  private String taxPayerId = null;

  @SerializedName("DBAName")
  private String dbAName = null;

  @SerializedName("GamingProfitsDistributions")
  private Boolean gamingProfitsDistributions = null;

  @SerializedName("IR35")
  private Boolean ir35 = null;

  @SerializedName("LastModifiedTimestamp")
  private DateTime lastModifiedTimestamp = null;

  public EmployeeEmploymentType effectiveStart(DateTime effectiveStart) {
    this.effectiveStart = effectiveStart;
    return this;
  }

   /**
   * Get effectiveStart
   * @return effectiveStart
  **/
 
  public DateTime getEffectiveStart() {
    return effectiveStart;
  }

  public void setEffectiveStart(DateTime effectiveStart) {
    this.effectiveStart = effectiveStart;
  }

  public EmployeeEmploymentType effectiveEnd(DateTime effectiveEnd) {
    this.effectiveEnd = effectiveEnd;
    return this;
  }

   /**
   * Get effectiveEnd
   * @return effectiveEnd
  **/
 
  public DateTime getEffectiveEnd() {
    return effectiveEnd;
  }

  public void setEffectiveEnd(DateTime effectiveEnd) {
    this.effectiveEnd = effectiveEnd;
  }

  public EmployeeEmploymentType employmentType(EmploymentTypeConfig employmentType) {
    this.employmentType = employmentType;
    return this;
  }

   /**
   * Get employmentType
   * @return employmentType
  **/
 
  public EmploymentTypeConfig getEmploymentType() {
    return employmentType;
  }

  public void setEmploymentType(EmploymentTypeConfig employmentType) {
    this.employmentType = employmentType;
  }

  public EmployeeEmploymentType taxPayerId(String taxPayerId) {
    this.taxPayerId = taxPayerId;
    return this;
  }

   /**
   * Get taxPayerId
   * @return taxPayerId
  **/
 
  public String getTaxPayerId() {
    return taxPayerId;
  }

  public void setTaxPayerId(String taxPayerId) {
    this.taxPayerId = taxPayerId;
  }

  public EmployeeEmploymentType dbAName(String dbAName) {
    this.dbAName = dbAName;
    return this;
  }

   /**
   * Get dbAName
   * @return dbAName
  **/
 
  public String getDbAName() {
    return dbAName;
  }

  public void setDbAName(String dbAName) {
    this.dbAName = dbAName;
  }

  public EmployeeEmploymentType gamingProfitsDistributions(Boolean gamingProfitsDistributions) {
    this.gamingProfitsDistributions = gamingProfitsDistributions;
    return this;
  }

   /**
   * Get gamingProfitsDistributions
   * @return gamingProfitsDistributions
  **/
 
  public Boolean getGamingProfitsDistributions() {
    return gamingProfitsDistributions;
  }

  public void setGamingProfitsDistributions(Boolean gamingProfitsDistributions) {
    this.gamingProfitsDistributions = gamingProfitsDistributions;
  }

  public EmployeeEmploymentType ir35(Boolean ir35) {
    this.ir35 = ir35;
    return this;
  }

   /**
   * Get ir35
   * @return ir35
  **/
 
  public Boolean getIr35() {
    return ir35;
  }

  public void setIr35(Boolean ir35) {
    this.ir35 = ir35;
  }

  public EmployeeEmploymentType lastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Get lastModifiedTimestamp
   * @return lastModifiedTimestamp
  **/
 
  public DateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeEmploymentType employeeEmploymentType = (EmployeeEmploymentType) o;
    return Objects.equals(this.effectiveStart, employeeEmploymentType.effectiveStart) &&
        Objects.equals(this.effectiveEnd, employeeEmploymentType.effectiveEnd) &&
        Objects.equals(this.employmentType, employeeEmploymentType.employmentType) &&
        Objects.equals(this.taxPayerId, employeeEmploymentType.taxPayerId) &&
        Objects.equals(this.dbAName, employeeEmploymentType.dbAName) &&
        Objects.equals(this.gamingProfitsDistributions, employeeEmploymentType.gamingProfitsDistributions) &&
        Objects.equals(this.ir35, employeeEmploymentType.ir35) &&
        Objects.equals(this.lastModifiedTimestamp, employeeEmploymentType.lastModifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(effectiveStart, effectiveEnd, employmentType, taxPayerId, dbAName, gamingProfitsDistributions, ir35, lastModifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeEmploymentType {\n");
    
    sb.append("    effectiveStart: ").append(toIndentedString(effectiveStart)).append("\n");
    sb.append("    effectiveEnd: ").append(toIndentedString(effectiveEnd)).append("\n");
    sb.append("    employmentType: ").append(toIndentedString(employmentType)).append("\n");
    sb.append("    taxPayerId: ").append(toIndentedString(taxPayerId)).append("\n");
    sb.append("    dbAName: ").append(toIndentedString(dbAName)).append("\n");
    sb.append("    gamingProfitsDistributions: ").append(toIndentedString(gamingProfitsDistributions)).append("\n");
    sb.append("    ir35: ").append(toIndentedString(ir35)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

