/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;



/**
 * EmployeePayrollTaxName
 */

public class EmployeePayrollTaxName {
  @SerializedName("TaxName")
  private String taxName = null;

  @SerializedName("Description")
  private String description = null;

  public EmployeePayrollTaxName taxName(String taxName) {
    this.taxName = taxName;
    return this;
  }

   /**
   * Get taxName
   * @return taxName
  **/
 
  public String getTaxName() {
    return taxName;
  }

  public void setTaxName(String taxName) {
    this.taxName = taxName;
  }

  public EmployeePayrollTaxName description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
 
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeePayrollTaxName employeePayrollTaxName = (EmployeePayrollTaxName) o;
    return Objects.equals(this.taxName, employeePayrollTaxName.taxName) &&
        Objects.equals(this.description, employeePayrollTaxName.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taxName, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeePayrollTaxName {\n");
    
    sb.append("    taxName: ").append(toIndentedString(taxName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

