/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;

/**
 * FederalFilingStatus
 */

public class FederalFilingStatus {
  @SerializedName("CountryCode")
  private String countryCode = null;

  @SerializedName("FederalFilingStatusCode")
  private String federalFilingStatusCode = null;

  @SerializedName("CalculationCode")
  private String calculationCode = null;

  @SerializedName("PayrollOutput")
  private String payrollOutput = null;

  @SerializedName("XRefCode")
  private String xrefCode = null;

  @SerializedName("ShortName")
  private String shortName = null;

  @SerializedName("LongName")
  private String longName = null;

  @SerializedName("LastModifiedTimestamp")
  private DateTime lastModifiedTimestamp = null;

  public FederalFilingStatus countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
 
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public FederalFilingStatus federalFilingStatusCode(String federalFilingStatusCode) {
    this.federalFilingStatusCode = federalFilingStatusCode;
    return this;
  }

   /**
   * Get federalFilingStatusCode
   * @return federalFilingStatusCode
  **/
 
  public String getFederalFilingStatusCode() {
    return federalFilingStatusCode;
  }

  public void setFederalFilingStatusCode(String federalFilingStatusCode) {
    this.federalFilingStatusCode = federalFilingStatusCode;
  }

  public FederalFilingStatus calculationCode(String calculationCode) {
    this.calculationCode = calculationCode;
    return this;
  }

   /**
   * Get calculationCode
   * @return calculationCode
  **/
 
  public String getCalculationCode() {
    return calculationCode;
  }

  public void setCalculationCode(String calculationCode) {
    this.calculationCode = calculationCode;
  }

  public FederalFilingStatus payrollOutput(String payrollOutput) {
    this.payrollOutput = payrollOutput;
    return this;
  }

   /**
   * Get payrollOutput
   * @return payrollOutput
  **/
 
  public String getPayrollOutput() {
    return payrollOutput;
  }

  public void setPayrollOutput(String payrollOutput) {
    this.payrollOutput = payrollOutput;
  }

  public FederalFilingStatus xrefCode(String xrefCode) {
    this.xrefCode = xrefCode;
    return this;
  }

   /**
   * Get xrefCode
   * @return xrefCode
  **/
 
  public String getXrefCode() {
    return xrefCode;
  }

  public void setXrefCode(String xrefCode) {
    this.xrefCode = xrefCode;
  }

  public FederalFilingStatus shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
 
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public FederalFilingStatus longName(String longName) {
    this.longName = longName;
    return this;
  }

   /**
   * Get longName
   * @return longName
  **/
 
  public String getLongName() {
    return longName;
  }

  public void setLongName(String longName) {
    this.longName = longName;
  }

  public FederalFilingStatus lastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Get lastModifiedTimestamp
   * @return lastModifiedTimestamp
  **/
 
  public DateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FederalFilingStatus federalFilingStatus = (FederalFilingStatus) o;
    return Objects.equals(this.countryCode, federalFilingStatus.countryCode) &&
        Objects.equals(this.federalFilingStatusCode, federalFilingStatus.federalFilingStatusCode) &&
        Objects.equals(this.calculationCode, federalFilingStatus.calculationCode) &&
        Objects.equals(this.payrollOutput, federalFilingStatus.payrollOutput) &&
        Objects.equals(this.xrefCode, federalFilingStatus.xrefCode) &&
        Objects.equals(this.shortName, federalFilingStatus.shortName) &&
        Objects.equals(this.longName, federalFilingStatus.longName) &&
        Objects.equals(this.lastModifiedTimestamp, federalFilingStatus.lastModifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, federalFilingStatusCode, calculationCode, payrollOutput, xrefCode, shortName, longName, lastModifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FederalFilingStatus {\n");
    
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    federalFilingStatusCode: ").append(toIndentedString(federalFilingStatusCode)).append("\n");
    sb.append("    calculationCode: ").append(toIndentedString(calculationCode)).append("\n");
    sb.append("    payrollOutput: ").append(toIndentedString(payrollOutput)).append("\n");
    sb.append("    xrefCode: ").append(toIndentedString(xrefCode)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    longName: ").append(toIndentedString(longName)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

