/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.my.dayforce.model.EVerify;

/**
 * I9Order
 */

public class I9Order {
  @SerializedName("I9OrderId")
  private String i9OrderId = null;

  @SerializedName("OrderStatusXRefCode")
  private String orderStatusXRefCode = null;

  @SerializedName("EVerify")
  private EVerify everify = null;

  public I9Order i9OrderId(String i9OrderId) {
    this.i9OrderId = i9OrderId;
    return this;
  }

   /**
   * Get i9OrderId
   * @return i9OrderId
  **/
 
  public String getI9OrderId() {
    return i9OrderId;
  }

  public void setI9OrderId(String i9OrderId) {
    this.i9OrderId = i9OrderId;
  }

  public I9Order orderStatusXRefCode(String orderStatusXRefCode) {
    this.orderStatusXRefCode = orderStatusXRefCode;
    return this;
  }

   /**
   * Get orderStatusXRefCode
   * @return orderStatusXRefCode
  **/
 
  public String getOrderStatusXRefCode() {
    return orderStatusXRefCode;
  }

  public void setOrderStatusXRefCode(String orderStatusXRefCode) {
    this.orderStatusXRefCode = orderStatusXRefCode;
  }

  public I9Order everify(EVerify everify) {
    this.everify = everify;
    return this;
  }

   /**
   * Get everify
   * @return everify
  **/
 
  public EVerify getEverify() {
    return everify;
  }

  public void setEverify(EVerify everify) {
    this.everify = everify;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    I9Order i9Order = (I9Order) o;
    return Objects.equals(this.i9OrderId, i9Order.i9OrderId) &&
        Objects.equals(this.orderStatusXRefCode, i9Order.orderStatusXRefCode) &&
        Objects.equals(this.everify, i9Order.everify);
  }

  @Override
  public int hashCode() {
    return Objects.hash(i9OrderId, orderStatusXRefCode, everify);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class I9Order {\n");
    
    sb.append("    i9OrderId: ").append(toIndentedString(i9OrderId)).append("\n");
    sb.append("    orderStatusXRefCode: ").append(toIndentedString(orderStatusXRefCode)).append("\n");
    sb.append("    everify: ").append(toIndentedString(everify)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

