/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;



/**
 * LaborCostTotalResult
 */

public class LaborCostTotalResult {
  @SerializedName("LaborCost")
  private Double laborCost = null;

  @SerializedName("LaborHours")
  private Double laborHours = null;

  public LaborCostTotalResult laborCost(Double laborCost) {
    this.laborCost = laborCost;
    return this;
  }

   /**
   * Get laborCost
   * @return laborCost
  **/
 
  public Double getLaborCost() {
    return laborCost;
  }

  public void setLaborCost(Double laborCost) {
    this.laborCost = laborCost;
  }

  public LaborCostTotalResult laborHours(Double laborHours) {
    this.laborHours = laborHours;
    return this;
  }

   /**
   * Get laborHours
   * @return laborHours
  **/
 
  public Double getLaborHours() {
    return laborHours;
  }

  public void setLaborHours(Double laborHours) {
    this.laborHours = laborHours;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LaborCostTotalResult laborCostTotalResult = (LaborCostTotalResult) o;
    return Objects.equals(this.laborCost, laborCostTotalResult.laborCost) &&
        Objects.equals(this.laborHours, laborCostTotalResult.laborHours);
  }

  @Override
  public int hashCode() {
    return Objects.hash(laborCost, laborHours);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LaborCostTotalResult {\n");
    
    sb.append("    laborCost: ").append(toIndentedString(laborCost)).append("\n");
    sb.append("    laborHours: ").append(toIndentedString(laborHours)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

