/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


import org.joda.time.DateTime;
import org.my.dayforce.model.Address;
import org.my.dayforce.model.Country;

/**
 * LegalEntity
 */

public class LegalEntity {
  @SerializedName("Country")
  private Country country = null;

  @SerializedName("LegalEntityAddress")
  private Address legalEntityAddress = null;

  @SerializedName("LegalIdNumber")
  private String legalIdNumber = null;

  @SerializedName("XRefCode")
  private String xrefCode = null;

  @SerializedName("ShortName")
  private String shortName = null;

  @SerializedName("LongName")
  private String longName = null;

  @SerializedName("LastModifiedTimestamp")
  private DateTime lastModifiedTimestamp = null;

  public LegalEntity country(Country country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
 
  public Country getCountry() {
    return country;
  }

  public void setCountry(Country country) {
    this.country = country;
  }

  public LegalEntity legalEntityAddress(Address legalEntityAddress) {
    this.legalEntityAddress = legalEntityAddress;
    return this;
  }

   /**
   * Get legalEntityAddress
   * @return legalEntityAddress
  **/
 
  public Address getLegalEntityAddress() {
    return legalEntityAddress;
  }

  public void setLegalEntityAddress(Address legalEntityAddress) {
    this.legalEntityAddress = legalEntityAddress;
  }

  public LegalEntity legalIdNumber(String legalIdNumber) {
    this.legalIdNumber = legalIdNumber;
    return this;
  }

   /**
   * Get legalIdNumber
   * @return legalIdNumber
  **/
 
  public String getLegalIdNumber() {
    return legalIdNumber;
  }

  public void setLegalIdNumber(String legalIdNumber) {
    this.legalIdNumber = legalIdNumber;
  }

  public LegalEntity xrefCode(String xrefCode) {
    this.xrefCode = xrefCode;
    return this;
  }

   /**
   * Get xrefCode
   * @return xrefCode
  **/
 
  public String getXrefCode() {
    return xrefCode;
  }

  public void setXrefCode(String xrefCode) {
    this.xrefCode = xrefCode;
  }

  public LegalEntity shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
 
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public LegalEntity longName(String longName) {
    this.longName = longName;
    return this;
  }

   /**
   * Get longName
   * @return longName
  **/
 
  public String getLongName() {
    return longName;
  }

  public void setLongName(String longName) {
    this.longName = longName;
  }

  public LegalEntity lastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
    return this;
  }

   /**
   * Get lastModifiedTimestamp
   * @return lastModifiedTimestamp
  **/
 
  public DateTime getLastModifiedTimestamp() {
    return lastModifiedTimestamp;
  }

  public void setLastModifiedTimestamp(DateTime lastModifiedTimestamp) {
    this.lastModifiedTimestamp = lastModifiedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegalEntity legalEntity = (LegalEntity) o;
    return Objects.equals(this.country, legalEntity.country) &&
        Objects.equals(this.legalEntityAddress, legalEntity.legalEntityAddress) &&
        Objects.equals(this.legalIdNumber, legalEntity.legalIdNumber) &&
        Objects.equals(this.xrefCode, legalEntity.xrefCode) &&
        Objects.equals(this.shortName, legalEntity.shortName) &&
        Objects.equals(this.longName, legalEntity.longName) &&
        Objects.equals(this.lastModifiedTimestamp, legalEntity.lastModifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, legalEntityAddress, legalIdNumber, xrefCode, shortName, longName, lastModifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegalEntity {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    legalEntityAddress: ").append(toIndentedString(legalEntityAddress)).append("\n");
    sb.append("    legalIdNumber: ").append(toIndentedString(legalIdNumber)).append("\n");
    sb.append("    xrefCode: ").append(toIndentedString(xrefCode)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    longName: ").append(toIndentedString(longName)).append("\n");
    sb.append("    lastModifiedTimestamp: ").append(toIndentedString(lastModifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

