/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.my.dayforce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;



/**
 * This class encapsulates the report data generated during the execution of the report.
 */

public class ReportColumnMetadata {
  @SerializedName("CodeName")
  private String codeName = null;

  @SerializedName("DisplayName")
  private String displayName = null;

  @SerializedName("DataType")
  private String dataType = null;

  public ReportColumnMetadata codeName(String codeName) {
    this.codeName = codeName;
    return this;
  }

   /**
   * CodeName is a unique name that can be used with code  to refer to this specific column.  Its value should be consistent.
   * @return codeName
  **/
 
  public String getCodeName() {
    return codeName;
  }

  public void setCodeName(String codeName) {
    this.codeName = codeName;
  }

  public ReportColumnMetadata displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * This is a name as defined by a user when developing this report.  This name  would be a human facing name that would be used on a printed report.  This field is used as the key to the values dictionary
   * @return displayName
  **/
 
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ReportColumnMetadata dataType(String dataType) {
    this.dataType = dataType;
    return this;
  }

   /**
   * This is a string representation of the data type.
   * @return dataType
  **/
 
  public String getDataType() {
    return dataType;
  }

  public void setDataType(String dataType) {
    this.dataType = dataType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportColumnMetadata reportColumnMetadata = (ReportColumnMetadata) o;
    return Objects.equals(this.codeName, reportColumnMetadata.codeName) &&
        Objects.equals(this.displayName, reportColumnMetadata.displayName) &&
        Objects.equals(this.dataType, reportColumnMetadata.dataType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codeName, displayName, dataType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportColumnMetadata {\n");
    
    sb.append("    codeName: ").append(toIndentedString(codeName)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

